// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-GdApGX0oj0GWYUgcnYb1SulJSCnnjo',
    appId: '1:747027818557:web:bd94fade51234b22e8a254',
    messagingSenderId: '747027818557',
    projectId: 'comp-3717-facerace',
    authDomain: 'comp-3717-facerace.firebaseapp.com',
    databaseURL: 'https://comp-3717-facerace-default-rtdb.firebaseio.com',
    storageBucket: 'comp-3717-facerace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHF7V8ZQxkLv5HQ6u15Wvfe-4N6WKIOHk',
    appId: '1:747027818557:android:23aac61af5ccf864e8a254',
    messagingSenderId: '747027818557',
    projectId: 'comp-3717-facerace',
    databaseURL: 'https://comp-3717-facerace-default-rtdb.firebaseio.com',
    storageBucket: 'comp-3717-facerace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnqXrgDO-rs2gU4KCm7qG2nyal-W2YLFA',
    appId: '1:747027818557:ios:966c81fb669ac3d6e8a254',
    messagingSenderId: '747027818557',
    projectId: 'comp-3717-facerace',
    databaseURL: 'https://comp-3717-facerace-default-rtdb.firebaseio.com',
    storageBucket: 'comp-3717-facerace.appspot.com',
    iosClientId: '747027818557-quo4o81vvsrn5a67vomqk02c1j6p6at5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flufi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnqXrgDO-rs2gU4KCm7qG2nyal-W2YLFA',
    appId: '1:747027818557:ios:966c81fb669ac3d6e8a254',
    messagingSenderId: '747027818557',
    projectId: 'comp-3717-facerace',
    databaseURL: 'https://comp-3717-facerace-default-rtdb.firebaseio.com',
    storageBucket: 'comp-3717-facerace.appspot.com',
    iosClientId: '747027818557-quo4o81vvsrn5a67vomqk02c1j6p6at5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flufi',
  );
}
